### ISSUE TITLE
დეშბორდის ავტოიზაციის პრობლემა

### ISSUE THREAD

**Issue by nika-chkhikvishvili** [nika-chkhikvishvili/smartchat#2]
http://dashboard-smartchat.cloud.gov.ge/  - დეშბორდში შესვლის დროს გენერირდება შეცდომა:

> An uncaught Exception was encountered
> 
> Type: RuntimeException
> 
> Message: Unable to locate the model you have specified: Login
> 
> Filename: /var/www/smartchat/dashboard/system/core/Loader.php
> 
> Line Number: 344
> 
> Backtrace:
> 
> File: /var/www/smartchat/dashboard/application/controllers/Welcome.php
> Line: 40
> Function: model
> 
> File: /var/www/smartchat/dashboard/index.php
> Line: 292
> Function: require_once

**Comment by frrrredo** [comment]
ეს ბაგი ონისემ უნდა მოაგვაროს და ჯერ არ მოუგვარებია, ასე რომ რომ ისევ ღიაა.

**Comment by frrrredo** [comment]
გიტჰაბთან სინქრონიზაციის პრობლემა იყო, მოგვარებულია.
