### ISSUE TITLE
node app

### ISSUE THREAD

**Issue by nika-chkhikvishvili** [nika-chkhikvishvili/smartchat#5]
ვერ ისტარტება, ეძებს არასებულ ცხრილს: **smartchat.person_tokens**

``` nodejs
Started:2016-05-14T00:31:40.694Z
{ [Error: ER_NO_SUCH_TABLE: Table 'smartchat.person_tokens' doesn't exist]
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  index: 0 }
```

არ ვიცი ვის გეხებათ ცხრილის დამატება, ამიტომ ვანიჭებ DBA-ს.

**Comment by kokaia** [comment]
სქლ ფაილი ჩავასწორე და ბაზა გააცარიელე და ისე გაუშვი და აღარ იქნება ეს შეცდომები

**Comment by frrrredo** [comment]
წვდომა ხომ გაქვს, ბაზაზე?

**Comment by frrrredo** [comment]
ბაზის განახლებამ უშველა.
